### ISSUE TITLE
Question about the compiler playlist in YouTube

### ISSUE THREAD

**Issue by stefanos82** [natalie-lang/natalie#1057]
Any idea how to watch the YouTube playlist in reverse chronological order, that is from older to newer?

**Comment by seven1m** [comment]
Hmmm... maybe I need to change the order  of the videos there? I will look...

**Comment by stefanos82** [comment]
Also, there are some private videos in playlist that need a sign in to view them `https://www.youtube.com/watch?v=_Cs_tZMDwyQ`, even though they are supposed to be hidden in playlist by default; I don't use YouTube account to view any view, I just watch whatever is available for me.

**Comment by seven1m** [comment]
OK I removed some videos that I had previously made private. Sorry about that.

I don't see a way to change the playlist order, unfortunately. Google pointed me to [this website](https://playlist.tools/) that will let you reverse the order yourself. Hope that helps!
