### ISSUE TITLE
Nightly spec runner no longer runs

### ISSUE THREAD

**Issue by herwinw** [natalie-lang/natalie#1106]
https://natalie-lang.org/specs

"The specs were completed at Thu, 01 Jun 2023 05:58:09 GMT"

**Comment by seven1m** [comment]
I think this is fixed now. The mounted storage for the stats API server had become disconnected, and restarting the container seems to have fixed it. If the stats post tonight, we can close this issue.

**Comment by herwinw** [comment]
Last update now shows "The specs were completed at Thu, 24 Aug 2023 05:18:17 GMT", so it had a recent run
