### ISSUE TITLE
Compile issues with GCC 13.2.0

### ISSUE THREAD

**Issue by herwinw** [natalie-lang/natalie#1425]
Compiling the current version of Natalie yields the following error on my system:
```
include/natalie/global_env.hpp:69:18: error: declaration of ‘Natalie::ClassObject* Natalie::GlobalEnv::Object()’ changes meaning of ‘Object’ [-Wchanges-meaning]
   69 |     ClassObject *Object() { return m_Object; }
      |                  ^~~~~~
include/natalie/global_env.hpp:25:9: note: used here to mean ‘class Natalie::Object’
   25 |         Object *object() { return m_object; }
      |         ^~~~~~
In file included from code/natalie/include/natalie/env.hpp:6:
include/natalie/forward.hpp:51:7: note: declared here
   51 | class Object;
      |       ^~~~~~
```
It looks like it is confusing the functions of `GlobalVariableInfo` and `GlobalEnv` that have the same name and are in the same file, but are otherwise unrelated. I'm not sure if this is a bug in Natalie, it feels like a compiler bug.

Since I'm probably the only one using this GCC version (gcc 13.2.0, Debian Sid), I'm self-assigning this. But since I'm simply using the workaround of compiling with Clang, it might take a while before I will actually look at this.

**Comment by stefanos82** [comment]
I get the same issue as you and I'm using Debian testing 64-bit with gcc 13.2.0 too if it offers some form of comfort for you.

**Comment by seven1m** [comment]
I upgraded Ubuntu on my desktop tonight and ran into this same issue. I'm kinda perplexed why moving that class out fixed it. :man_shrugging:

**Comment by stefanos82** [comment]
I managed to compile it with `clang 16.0.6` by simply executing `CXX=clang++ rake`.

The only problem was testing it via `bin/natalie examples/hello.rb`; it produced the same error messages as above.

**Comment by herwinw** [comment]
@stefanos82 That's probably because running the example tries to use `g++` again. Running it like `CXX=clang++ bin/natalie examples/hello.rb` should resolve that (or just run `export CXX=clang++` in the shell, so you don't have to repeat it every single command).

**Comment by stefanos82** [comment]
I would have never thought of doing that @herwinw :smile: indeed this works. I will write it down to remember it for future purposes; you never know when I might need it!

Thank you my friend :+1:
