### ISSUE TITLE
Upgrade clang-tidy and fix warnings

### ISSUE THREAD

**Issue by seven1m** [natalie-lang/natalie#1472]
We currently run clang-tidy in the Ubuntu 20.04 image on GitHub Actions, which means it's kinda old. Newer versions of clang-tidy have been known to catch things in our code, e.g. #1462.

It would be cool to:

1. Run `rake docker_tidy` locally and fix any warnings.
2. Have our CI (GitHub Actions) run our `rake docker_tidy` task. I believe this will let us run a newer version of clang-tidy. (If not, maybe see about what it would take to upgrade our Docker image to newer Ubuntu version.)

**Comment by herwinw** [comment]
The change in #1492 resolves the current issue, clang-tidy now runs successfully on my machine. The only step left should be to run it in the CI.

**Comment by herwinw** [comment]
https://github.com/natalie-lang/natalie/actions/runs/6915553353/job/18814621284?pr=1507#step:4:109

Yeah, this still uses 14
