### ISSUE TITLE
OpenSSL Digest reset issue on macOS (OpenSSL 3.2?)

### ISSUE THREAD

**Issue by seven1m** [natalie-lang/natalie#1575]
I suspect this is due to some change in OpenSSL 3.2 ... but it happens regularly in our CI and on my local Mac. See failed build here: https://github.com/natalie-lang/natalie/actions/runs/7152408867/job/19477709455

I did some debugging and found that I can get this test to pass:

https://github.com/natalie-lang/natalie/blob/master/spec/library/digest/sha512/hexdigest_spec.rb

...if I comment out this line in the spec:

https://github.com/natalie-lang/natalie/blob/master/spec/library/digest/sha512/hexdigest_spec.rb#L8

```ruby
cur_digest = Digest::SHA512.new

# Commenting this line fixes the spec:
cur_digest.hexdigest.should == SHA512Constants::BlankHexdigest

# Maybe need to reset something before we can call this again...
cur_digest << "test"
```

...or if I comment out this line in our implementation:

https://github.com/natalie-lang/natalie/blob/master/lib/openssl.cpp#L264

```cpp
if (args.size() == 1)
    OpenSSL_Digest_reset(env, self, {}, nullptr);

// changing to this works:
OpenSSL_Digest_reset(env, self, {}, nullptr);
```

In both cases, it seems that after we call `EVP_DigestFinal_ex`, we should be calling `OpenSSL_Digest_reset` or perhaps `EVP_MD_CTX_cleanup` according to Google.

I don't know enough about how OpenSSL works to know which is correct. @herwinw any thoughts?

**Comment by herwinw** [comment]
I'll have a look at it tomorrow
