### ISSUE TITLE
Hash#replace with self

### ISSUE THREAD

**Issue by seven1m** [natalie-lang/natalie#1620]
I accidentally called Hash#replace with ~a copy of~ itself and found this bug:

```ruby
h = { foo: 'bar' }
p h.replace(h)
p h
```

With CRuby:

```
{:foo=>"bar"}
{:foo=>"bar"}
```

With Natalie:

```
{}
{}
```

**Comment by herwinw** [comment]
> a copy of itself

I think this description is inaccurate: when using a copy (like `h.replace(h.dup)`), it works as expected. This bug triggers when you specifically use the same object.

**Comment by herwinw** [comment]
```ruby
a = [1, 2, 3]
p a.replace(a)
p a
```
Arrays have the same issue.

```ruby
s = 'hello, world'
p s.replace(s)
p s
````
But Strings doe not have this issue.
