### ISSUE TITLE
Easier way to convert IntegerObject to a native type

### ISSUE THREAD

**Issue by herwinw** [natalie-lang/natalie#1930]
We have a lot of code converting a Ruby Integer to a C integer to use in lower level C calls. The code mostly looks like this:
```c++
const auto x = IntegerObject::convert_to_nat_int_t(env, y);
// or:
const auto x = y->to_int(env)->to_nat_int_t();
```
This has two problems:
1. The object may be a bigint, this causes an assertion error and stops your program
2. The resulting value is a `long long`, which may exceed the limits of the actual C type we need. This is often used for a max size, that should not be negative, but also a lot of call sites can't handle numbers exceeding integer limit.

So I kind of want something like this:
```c++
template <typename T>
static T IntegerObject::convert_to_native_type<T>(env, Value in) {
  IntegerObject *in_as_integer = in->to_int(env); // This handles #to_int conversion as well, and raises a TypeError for not Integer
  if (in_as_integer->is_bignum())
    env->raise("Exception for bignum");
  const auto result = in_as_integer->to_nat_int_t();
  if (result < std::numeric_limits<T>::min())
    env->raise("Exception for too small");
  // Same as above for ::max
  return static_cast<T>(result);
}
```
MRI has some conversion (I tested this with `UDPSocket#recvfrom_nonblock`). Some output for unaccepted values:
```
bignum too big to convert into `long' (RangeError)
integer 2305843009213693952 too big to convert to `int' (RangeError)
integer -2305843009213693952 too small to convert to `int' (RangeError)
negative string size (or size too big) (ArgumentError)
```

I'm not sure whether we should replicate that last statement, we probably want to use `size_t` instead of `int` as the native type and catch this before trying to build a buffer.

It would be nice to use some kind of reflection/type info to convert the `T` to the string `int`, https://en.cppreference.com/w/cpp/types/type_info/name does something close but not the exact thing that we need.

**Comment by seven1m** [comment]
You're very right. This seems like a hood idea to me!
