### ISSUE TITLE
Implement Array#pack

### ISSUE THREAD

**Issue by seven1m** [natalie-lang/natalie#195]
1. Remove "skip-test" comment from top of a `spec/core/array/pack/*_spec.rb` file.
2. Modify ArrayPacker and/or StringPacker to make the specs pass
3. Commit! (EASY! :laughing:)

- [x] a_spec.rb
- [x] at_spec.rb
- [x] b_spec.rb
- [x] buffer_spec.rb
- [x] comment_spec.rb
- [x] c_spec.rb
- [x] d_spec.rb
- [x] empty_spec.rb
- [x] e_spec.rb
- [x] f_spec.rb
- [x] g_spec.rb
- [x] h_spec.rb
- [x] i_spec.rb
- [x] j_spec.rb
- [x] l_spec.rb
- [x] m_spec.rb
- [x] n_spec.rb
- [x] percent_spec.rb
- [x] p_spec.rb
- [x] q_spec.rb
- [x] s_spec.rb
- [x] u_spec.rb
- [x] v_spec.rb
- [x] w_spec.rb
- [x] x_spec.rb
- [x] z_spec.rb

**Comment by Crystalsage** [comment]
@seven1m It seems that directives n+N and p+P  have been implemented in PR #668. We can check them off the list.

**Comment by seven1m** [comment]
🎉
