### ISSUE TITLE
Occasional issue with conditionvariable specs

### ISSUE THREAD

**Issue by herwinw** [natalie-lang/natalie#1966]
Example: https://github.com/natalie-lang/natalie/actions/runs/8569056088/job/23484139786
```
 FAIL ruby/spec::spec/core/conditionvariable/signal_spec.rb#test_0001_passes all specs (2901.91s)
        Expected #<Process::Status: pid 18873 exit 1> to be success?.
        /natalie/test/ruby/ruby_specs_test.rb:35:in `block (4 levels) in <top (required)>'
```
Once in a while this spec fails. Most times a retry resolves this issue, but it would be nice to not have this issue in the first place.

**Comment by herwinw** [comment]
Not sure if it is related, but the MacOS test is often taking about 2h30m to finish, which is roughly double that of the Linux runs.

**Comment by herwinw** [comment]
I'm tempted to close this one, I can't remember having seen this issue in a long time, so I guess it has been fixed by accident (either because we fixed something else, or an update of something in the toolchain on Darwin)

**Comment by seven1m** [comment]
It happened here: https://github.com/natalie-lang/natalie/actions/runs/9429844956/job/25976667355 😭

**Comment by seven1m** [comment]
I cannot find the logs for this bug, but I think it's the same as #2340.
