### ISSUE TITLE
build failed on raspbian (armhf)

### ISSUE THREAD

**Issue by phykos** [natalie-lang/natalie#2]
[build-errors.txt](https://github.com/seven1m/natalie/files/4474384/build-errors.txt)

**Comment by seven1m** [comment]
If I am not mistaken, armhf is 32-bit. That seems to jive with the error message about casting a (32-bit) pointer to a 64-bit integer.

I haven't put any thought into supporting 32-bit architectures, but I don't think I care to worry about it at this early stage.

**Comment by phykos** [comment]
ok, thanks anyway.
btw I cloud try to let it run also on 32 bit machines

**Comment by phykos** [comment]
I literally fixed 2 errors and got like 10 new errors.
at least I tried

**Comment by seven1m** [comment]
Let's keep this open. Someday we can work on it... 😉

**Comment by seven1m** [comment]
Just being real here, this is not a high priority for me, sadly. 32-bit architecture is slowly going away, and I don't think I have the motivation to figure this out now or in the near future. I'm ok with saying we only support 64-bit for now.

(I know I'm the one who decided to keep this issue open all this time, so I'm basically just talking to myself now. :laughing:)
