### ISSUE TITLE
Implement methods of Integer

### ISSUE THREAD

**Issue by richardboehme** [natalie-lang/natalie#201]
Our main approach is to work on one spec from [ruby/spec](https://github.com/ruby/spec/tree/master/core/integer) at a time, implementing as much of the spec as possible, then check it off the list:

- [x] abs_spec.rb
- [x] allbits_spec.rb
- [x] anybits_spec.rb
- [x] bit_and_spec.rb
- [x] bit_length_spec.rb
- [x] bit_or_spec.rb
- [x] bit_xor_spec.rb
- [x] case_compare_spec.rb
- [x] ceil_spec.rb
- [x] chr_spec.rb
- [x] coerce_spec.rb
- [x] comparison_spec.rb
- [x] complement_spec.rb
- [x] constants_spec.rb
- [x] denominator_spec.rb
- [x] digits_spec.rb
- [x] div_spec.rb
- [x] divide_spec.rb
- [x] divmod_spec.rb
- [x] downto_spec.rb
- [x] dup_spec.rb
- [x] element_reference_spec.rb
- [x] equal_value_spec.rb
- [x] even_spec.rb
- [x] exponent_spec.rb
- [x] fdiv_spec.rb
- [x] floor_spec.rb
- [x] gcd_spec.rb
- [x] gcdlcm_spec.rb
- [x] gt_spec.rb
- [x] gte_spec.rb
- [x] integer_spec.rb
- [x] lcm_spec.rb
- [x] left_shift_spec.rb
- [x] lt_spec.rb
- [x] lte_spec.rb
- [x] magnitude_spec.rb
- [x] minus_spec.rb
- [x] modulo_spec.rb
- [x] multiply_spec.rb
- [x] next_spec.rb
- [x] nobits_spec.rb
- [x] numerator_spec.rb
- [x] odd_spec.rb
- [x] ord_spec.rb
- [x] plus_spec.rb
- [x] pow_spec.rb
- [x] pred_spec.rb
- [x] rationalize_spec.rb
- [x] remainder_spec.rb
- [x] right_shift_spec.rb
- [x] round_spec.rb
- [x] size_spec.rb
- [x] sqrt_spec.rb
- [x] succ_spec.rb
- [x] times_spec.rb
- [x] to_f_spec.rb
- [x] to_i_spec.rb
- [x] to_int_spec.rb
- [x] to_r_spec.rb
- [x] to_s_spec.rb
- [x] truncate_spec.rb
- [x] try_convert_spec.rb
- [x] uminus_spec.rb
- [x] upto_spec.rb

**Comment by ryangjchandler** [comment]
I believe the only thing holding back `Integer#to_s` is the `Encoding` related specs - I assume we can say it's spec-compliant since we'll only be implementing common encodings right @seven1m?

**Comment by seven1m** [comment]
Yeah let's just do what we can with the encodings we have currently and call it done. Liberally sprinkle `NATFIXME` where needed, and we can come back later and fix!

**Comment by richardboehme** [comment]
I think we completed most of the stuff that we can do right now. Do we want to close this?

**Comment by seven1m** [comment]
Awesome!!!!

**Comment by seven1m** [comment]
@richardboehme I'll let you do the honors. 🥰

**Comment by seven1m** [comment]
🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉
