### ISSUE TITLE
[Documentation] Natalie in 5 years?

### ISSUE THREAD

**Issue by rubyFeedback** [natalie-lang/natalie#2237]
So, this issue can be closed just fine - it is mostly a question.

I have been following natalie on and off for a while, as a casual observer.

Obviously the primary goal is to have a working ruby interpreter ready,
in C++ (I suppose) and following most of the spec or all of the spec. I
guess that goal will eventually be achieved, sooner or later. The last 
10% always take more than the first 10% - something like that. :)

However had, what is beyond that step? For instance, could natalie
be used similar to mruby, where people could cherry-pick what 
their own "customized" natalie be like? A bit like modularity that
can be seen not only in mruby, but in the linux kernel or the
busybox toolkit - the latter I like because I can compile busbox
statically and it would be pretty great to have natalie also be
compiled statically (in a minimal variant). That could help for
fixing issues on a computer using ruby, rather than e. g. 
shell scripts. But I am sure there are many more use cases people
may have - so what I am basically asking in this issue is some kind
of "meta-goal" for natalie in the semi-medium future.

Anyway - perhaps if you feel up to some thoughts written down as
text, this may be interesting for several people, not just me. It could
be published on the homepage, or somewhere else and linked to.
Right now most people probably just look at the progress of the
implementation but some may think "and then what".

**Comment by seven1m** [comment]
I don't have a plan. Never have! I enjoy working on hard things, and this is about the hardest thing I could think to build. That's about it. I have a little manifesto site that might explain my personal motivation: https://justforfunnoreally.dev/

Of course I don't speak for others who work or have worked on the project.

I don't have a roadmap. My one "goal" if you could call it that would be to be able to compile a Sinatra application down to a binary and deploy it as a self-contained web application in a single file. That would be pretty nifty.

But I don't have grand visions for Natalie being used by anyone serious, honestly. The only way that could happen is if we got a big fat corporate sponsorship and some full time people working on it. And personally that doesn't even sound fun to me for some reason. (But I would wholeheartedly say "have fun!" if someone else got a full time working on this project or some derivative of it.)

Sorry to disappoint. People ask this a lot. It's basically a more sophisticated version of "why." I still don't have an answer other than, "it's fun!" ❤️

**Comment by herwinw** [comment]
It's very much the same thing for me: I enjoy working on it from time to time, but I see this very much as a toy project that I would never use it to run anything production level.
Occasionally, I ask myself if it would be better to spend my time working on CRuby or JRuby instead, since that would affect more people, but somehow I always end up back here. And since we've added enough upstream rubyspecs originating in this project, I can fully justify that to myself.

Also, if someone would start paying me to work on Natalie, I would probably lose the fun in it pretty quickly.
