### ISSUE TITLE
Write CSV specs

### ISSUE THREAD

**Issue by richardboehme** [natalie-lang/natalie#551]
Due to [ruby/spec](https://github.com/ruby/spec) lacking specs for most of the CSV library, we want to provide our own specs (with the goal of upstreaming those to ruby/spec). Currently the following methods of CSV are implemented in Natalie and need specs:

- [ ] initialize
- [x] self.generate
- [x] self.generate_line
- [ ] self.open
- [x] self.parse
- [x] <<
- [x] add_row
- [x] col_sep
- [ ] each
- [ ] headers
- [x] liberal_parsing?
- [ ] lineno
- [ ] parser
- [ ] read
- [ ] readline
- [x] readlines
- [ ] rewind
- [x] row_sep
- [ ] shift

**Comment by seven1m** [comment]
I think I might close this issue. It's a big broad and feels like it's not going to happen in my lifetime. I'm happy with where our CSV library is for now, and I'd rather just fix bugs as they come up. @richardboehme do you have thoughts?

**Comment by richardboehme** [comment]
> I think I might close this issue. It's a bit broad and feels like it's not going to happen in my lifetime. I'm happy with where our CSV library is for now, and I'd rather just fix bugs as they come up. @richardboehme do you have thoughts?

I originally opened the issue because I felt the CSV implementation I built was pretty barebones and I wanted us to investigate more edge cases and eventually contribute those specs to ruby/spec. However I totally understand where you are coming from and I'd be fine with the issue being closed! :heart:

**Comment by seven1m** [comment]
Thanks for the quick feedback. By all means, if you (or anyone else reading) feels ambitious and wants to add more specs for the csv library, please do! We can open smaller issues and PRs to address bits of it as we feel inspiration. Thanks @richardboehme!

**Comment by herwinw** [comment]
I just ran the full upstream specs with Ruby 3.3.0-preview2 and noticed this warning:
```
warning: csv which will be not part of the default gems since Ruby 3.4.0
```
So I guess the CSV lib will be removed from the specs soon-ish. I don't think we should write new specs for it (which we weren't planning to do, since this case is closed)

**Comment by seven1m** [comment]
Oh wow! Good to know.
