### ISSUE TITLE
Implement TCPServer and TCPSocket

### ISSUE THREAD

**Issue by seven1m** [natalie-lang/natalie#598]
I'd like to eventually host https://natalie-lang.org with Natalie, so we'll need some socket stuff!

Here is the initial program I'd like to get running: https://gist.github.com/seven1m/9d18479b4e0ddd5fa71b06a8b6bb166b From there I think we can serve up a static file rather than the 'hello world' string.

I'll add more notes to this issue as I learn more... :hugs:

Checklist (growing as we learn):
- [ ] Socket.tcp
  - [x] `spec/library/socket/socket/tcp_spec.rb`
- [ ] Addrinfo
  - [x] `spec/library/socket/addrinfo/initialize_spec.rb`
  - [x] `spec/library/socket/addrinfo/ip_address_spec.rb`
  - [x] `spec/library/socket/addrinfo/ip_port_spec.rb`
  - [x] `spec/library/socket/addrinfo/to_sockaddr_spec.rb`
- [ ] BasicSocket
  - [x] `spec/library/socket/basicsocket/setsockopt_spec.rb`
  - [x] `spec/library/socket/basicsocket/getsockopt_spec.rb`
  - [x] `spec/library/socket/basicsocket/getsockname_spec.rb`
  - [x] `spec/library/socket/basicsocket/recv_spec.rb`
- [ ] Socket
  - [x] `spec/library/socket/socket/getaddrinfo_spec.rb`
  - [x] `spec/library/socket/socket/accept_spec.rb`
- [ ] IPSocket
  - [x] `spec/library/socket/ipsocket/addr_spec.rb`
- [ ] TCPServer
  - [x] `spec/library/socket/tcpserver/new_spec.rb`
  - [x] `spec/library/socket/tcpserver/accept_spec.rb`
- [ ] TCPSocket
  - [x] `spec/library/socket/tcpsocket/initialize_spec.rb`

**Comment by ryangjchandler** [comment]
Perhaps we could add a new compiler macro that lets you embed the contents of a file in an executable, similar to Rust's `include_str!()` macro or `#include` in CXX.

**Comment by seven1m** [comment]
@ryangjchandler that's sick!

**Comment by TheGrizzlyDev** [comment]
> That way it really is self-contained and there's no need for file I/O at runtime..
You'd still have the test results, right? Regardless, it's such a great idea!

**Comment by ryangjchandler** [comment]
@TheGrizzlyDev Yeah, I'm mainly talking about the landing / home page of the site.

**Comment by seven1m** [comment]
It works! We can now run [examples/webserver.rb](https://github.com/natalie-lang/natalie/blob/master/examples/webserver.rb) using the new Socket primitives. 🥰
