### ISSUE TITLE
Implement methods of `Complex`

### ISSUE THREAD

**Issue by ryangjchandler** [natalie-lang/natalie#608]
Our main approach is to work on one spec from [ruby/spec](https://github.com/ruby/spec/tree/master/core/complex) at a time, implementing as much of the spec as possible, then check it off the list:

* [x] abs2_spec.rb
* [x] abs_spec.rb
* [x] angle_spec.rb
* [x] arg_spec.rb
* [x] coerce_spec.rb
* [x] comparison_spec.rb
* [x] conj_spec.rb
* [x] conjugate_spec.rb
* [x] constants_spec.rb
* [x] denominator_spec.rb
* [x] divide_spec.rb
* [x] eql_spec.rb
* [x] equal_value_spec.rb
* [x] exponent_spec.rb
* [x] fdiv_spec.rb
* [x] finite_spec.rb
* [x] hash_spec.rb
* [x] imag_spec.rb
* [x] imaginary_spec.rb
* [x] infinite_spec.rb
* [x] inspect_spec.rb
* [x] integer_spec.rb
* [x] magnitude_spec.rb
* [x] marshal_dump_spec.rb
* [x] minus_spec.rb
* [x] multiply_spec.rb
* [x] negative_spec.rb
* [x] numerator_spec.rb
* [x] phase_spec.rb
* [x] plus_spec.rb
* [x] polar_spec.rb
* [x] positive_spec.rb
* [x] quo_spec.rb
* [x] rationalize_spec.rb
* [x] real_spec.rb
* [x] rect_spec.rb
* [x] rectangular_spec.rb
* [x] to_c_spec.rb
* [x] to_f_spec.rb
* [x] to_i_spec.rb
* [x] to_r_spec.rb
* [x] to_s_spec.rb
* [x] uminus_spec.rb

**Comment by herwinw** [comment]
Most of these have been fixed by now, the only one remaining is `exponent_spec.rb` where I've gotten kind of confused by the math behind it. The rest of the specs is equal to the current version of ruby_spec.

**Comment by ryangjchandler** [comment]
@herwinw I'm gonna sort the exponent one tonight :^) The math is a little complex (no pun intended), I have to admit.

**Comment by ryangjchandler** [comment]
I believe this one is all done now, whoop! 🎉

**Comment by seven1m** [comment]
Thanks for all your work on this everybody! ❤️
