### ISSUE TITLE
[Suggestion and Notice] GUI + Natalie + Libui

### ISSUE THREAD

**Issue by rubyFeedback** [natalie-lang/natalie#618]
Hey there Tim,

I am just a random ruby hacker - just ruby, no C. C is above my head. ;)

Anyway. I wrote quite a lot of ruby-gtk code over the years, and of course
ruby. Actually ruby-gtk got me interested in GUIs.

Do you know libui and the bindings maintained by kojix2? You can see his
project there:

https://github.com/kojix2/LibUI

Libui is a bit limited, but you can do "gem install libui" on windows and just
use ruby with basic GUI stuff there. \o/

How did I find you? Actually randomly via google, I landed up on this video:

https://www.youtube.com/watch?v=m-FEuur8xLo

At first I didn't even know why I was landing there. I searched mostly for
ruby-gtk4, because the new signal handling confuses me (in ruby-gtk3
it was simpler, in ruby-gtk4 I struggle). Anyway. That's not why I write
this here, I just want to give a background.

Via libui and kojix2, I found Andy's glimmer. Not sure if you heard about
it but the idea - or I describe it - is to run a GUI EVERYWHERE. :D

Andy also does videos, so it reminded me a bit about you.

Here is his blog:

https://andymaleh.blogspot.com/

And his github in case you don't know him yet:

https://github.com/AndyObtiva/

His youtube videos reminded me a bit of the C-gtk stuff you did,
though Andy is more a ruby guy + Java than C.

Either way you both do videos.

Ok, so now what does this all have to do with natalie.

Well - I don't know how far you progressed with natalie (I didn't
watch any other video yet, except for your last one from 4 weeks
ago).

Could you either do a video for Natalie + GUI (can be anything
including www), and/or links and especially example code that
works for GUI-related stuff? This does not have to be anything
fancy, just basic things. Just to showcase Natalie and GUI stuff.

It would be kind of neat to see smaller example code (in .rb
files or anything else) for Natalie.

**Comment by seven1m** [comment]
@rubyFeedback thanks for the note! I appreciate the feedback.

Natalie has a very rudimentary wrapper for GTK3, but it's nowhere near complete. Honestly, right now, my focus is on getting low level Sockets to work so I can build a web server. :smile: 

I would love to host the https://natalie-lang.org website with Natalie.

But yes, I will try to do some sort of GUI video in the future. Thanks so much for your interest in the project! :heart:
