### ISSUE TITLE
Sinatra / .cgi example?

### ISSUE THREAD

**Issue by rubyFeedback** [natalie-lang/natalie#621]
Hey there Tim,

I see you are working on sockets-related stuff at
https://github.com/natalie-lang/natalie/tree/master/examples.

(Kind of semi-random how I found natalie indirectly via ending
up on a youtube video about gtk. But seeing the modus operandi
how to work is interesting; I am a rubyist without real C/C++ 
knowledge, so that was interesting to see how ruby can be
used from another point of view, e. g. the terminal-speific
and vim-specific focus on ruby indirectly via C++ and tons of
recompiling steps)

Would it be possible to also add/use/showcase one example
(or perhaps two, if you want to separate this) for sinatra and
.cgi?

.cgi is old, perhaps outdated, I get it, but it would still be nice
to see that Natalie can do be used for a simple .cgi file. I
really only mean a "hello world" example there, does not have
to implement/use all of .cgi really.

The second request via this issue is to ask for a similar example
with sinatra. So, a hello world, and perhaps also a demo for
a SIMPLE route such as:

    /hello/NAME
    /hello/tim

Just to showcase it. So really just the equivalent "hello world" 
examples.

I know time is a limited/finite resource and there may be more
important things from a top-down design point of view (e. g.
the specification), but from a user's point of view I think this
would be nice, since we could then say "natalie works for
simple .cgi/sinatra" examples. A bit similar to the code you 
used to showcase gtk (gtk3).

Either way thanks for reading - this can be done at some later
time of course, I don't mean to imply that this has to be done
now.  But perhaps you get bored after xmas celebrations
at one point in time in a few months ... :D

**Comment by seven1m** [comment]
CGI is doable now, but Sinatra will be a huge undertaking, and probably still a long ways off. There's a lot of core functionality and standard library things we would need to add to get Rack and Sinatra working. Thanks for your interest, I'll keep chipping away at it!
