### ISSUE TITLE
[Documentation] Could the README mention limitations of the entry point "Compile a file to an executable"?

### ISSUE THREAD

**Issue by rubyFeedback** [natalie-lang/natalie#706]
Right now the README states:

    Compile a file to an executable:

    bin/natalie examples/hello.rb -c hello
    ./hello

But I assume there may be some limitations. Perhaps some more advanced .rb files
may break; perhaps when some gems are used; or perhaps when one uses windows
or something of this nature.

It would be nice to be able to read a bit more information in this regard in the main
README, or another doc/ file if you want to linked in to from the main README.

Thank you for reading this documentation-centric request.

**Comment by seven1m** [comment]
Yes, there are a lot of limitations! I think that is covered in the readme by saying "Natalie is a very early-stage work-in-progress Ruby implementation." If we have to start listing things Natalie cannot yet do, the list will be quite large!

The list of things Natalie cannot do is shrinking every day, but it is still quite a lot. Thanks for taking a look at our project!
