### ISSUE TITLE
Wrong behavior when defining `new` with another class initializer

### ISSUE THREAD

**Issue by richardboehme** [natalie-lang/natalie#718]
The following code should return `String` but does return `MethodHolder`

```ruby
class MethodHolder
  class << self
    define_method(:new, &String.method(:new))
  end
end

p MethodHolder.new.class
```

**Comment by richardboehme** [comment]
I recently made some tries to make `define_method` spec compliant. However, all of them failed. The main problem is that we cannot differentiate between a block like `&String.method(:new)` and a block like `{ "" }`. The first one should evaluate with self being the String class while the second should be evaled in the scope of the Module where `define_method` is called.

I think we might need to store some type on the Block to differentiate between the different evaluation contexts. Right now we have a ProcType (which can be either block or lambda). We could use this, but we would need to move it to Block and extend it with something like `BlockType::Method`. 

What do you think? @seven1m

**Comment by seven1m** [comment]
Yep, agreed! I tried to fix this recently and came to the same conclusion.
