### ISSUE TITLE
Move the TM library/namespace into its own separate repository

### ISSUE THREAD

**Issue by herwinw** [natalie-lang/natalie#758]
Actually more of a suggestion of an issue.

There are two copies of the TM lib (`include/tm/`): both Natalie and Natalie-parser have their own folder.  These folder are currently diverging, since I've pushed a couple of improvements to the TM libs of Natalie, so now these files have to be copied over to Natalie-parser to use them over there as well.

I think this could be resolved by creating a separate repository for the TM libs, and use git submodules to share them with both projects. It could have its own set of tests (see my remark in https://github.com/natalie-lang/natalie/pull/754#issuecomment-1365063146)

**Comment by seven1m** [comment]
It comes from this library: https://github.com/seven1m/tm

I periodically go through and sync up the code.

**Comment by herwinw** [comment]
Well, they're submodules now, so I guess we can close this one.
