### ISSUE TITLE
Occasional error in string/valid_encoding_spec

### ISSUE THREAD

**Issue by herwinw** [natalie-lang/natalie#794]
Once in a while this spec fails an assertion in the string view lib:
```
natalie/ext/tm/include/tm/string_view.hpp:82: TM::StringView::StringView(const TM::String*, size_t, size_t):
  Assertion `length <= string->length() - offset' failed
```
I first noticed it at the run of https://github.com/natalie-lang/natalie/actions/runs/3855961756/jobs/6571602668. I just tried to run the spec 20 times in a row and it failed once.

This feels like a deeper inner issue instead of an error in this specific spec.

**Comment by seven1m** [comment]
I was just looking at this. Thanks for documenting it. I'll try to investigate soon.
