### ISSUE TITLE
Fix protected methods

### ISSUE THREAD

**Issue by seven1m** [natalie-lang/natalie#870]
While working on ChunkyPNG, I ran across a bug with protected methods. Say you have the following code:

```ruby
# wat.rb

class Foo
  protected

  def protected_method
    'protected'
  end
end

class Bar < Foo
  def public_method
    f = Foo.new
    f.protected_method
  end
end

p Bar.new.public_method # => 'protected'
```

This works in MRI, but not with Natalie:

```sh
→ ruby wat.rb
"protected"
                                                                                                                                                                           
→ bin/natalie wat.rb
Traceback (most recent call last):
        1: from wat.rb:16:in `<main>'
wat.rb:12:in `public_method': protected method `protected_method' called for #<Foo:0x5bad282e39a0                                                                                                 
> (NoMethodError)
```

**Comment by seven1m** [comment]
This is going to be difficult. 😢 

We decide to use `send()` or `public_send()` at compile time -- not at run time. But since the compiler doesn't know the type of the `f` object, we're going to have to determine visibility at run time, which sucks.

And a simple object comparison won't work, because we need to check each of the ancestors. This is going to slow down the runtime considerably, since it happens on every method call.

I really dislike this "feature", I have to say. 😭

**Comment by ryangjchandler** [comment]
@seven1m I might be missing something here so please correct me if I'm wrong...

Since protected methods can only be called from the inherited context and not outside of it, we could presumably have an additional `protected_send()` or similar that only gets produced by the compiler in the context of a method, right?

e.g.

```rb
class Foo
	protected
	def bar
		"bar"
	end
end

class Baz < Foo
  def call_bar
    # This would use some sort of "internal_send".
    bar
  end
end

baz = Baz.new

p baz.call_bar

# This would still go through regular send/public_send and throw `NoMethodError`
p baz.bar
```

**Comment by seven1m** [comment]
I did think of something that might help with the perf issue... we only need to check the object class and its ancestors if the method call would otherwise result in a NoMethodError. That is to say, this extra bit of work shouldn't need to happen in the happy path -- only when we think the method is private/protected and we're about to give up, then we can fall back to the slow object comparison. 🤔

**Comment by seven1m** [comment]
To clarify:

1. If using `private_send()`, there will be no performance penalty.
2. If using `send()`, and the method is public, there will be no performance penalty.
3. If using `send()`, and the method is private/protected, just before we raise NoMethodError, we can do an extra check to see if the "sent from" object's ancestors include the receiving object, and if so, then let the method call go through.

At least, that works in my head. I'll fiddle with it!
