### ISSUE TITLE
Evaluation order of receiver and arguments is backwards

### ISSUE THREAD

**Issue by herwinw** [natalie-lang/natalie#873]
One of the leftovers of #862, where this code caused issues:
```ruby
(set = Set[]) << set
```
This raises an error (backtrace from commit 490d07224b66a98db6fb297ab475204a73ceb54a):
```
lib/natalie/compiler/instructions/variable_get_instruction.rb:48:in `generate': variable not defined set (RuntimeError)
	from lib/natalie/compiler/backends/cpp_backend/transform.rb:31:in `block in transform'
	from lib/natalie/compiler/instruction_manager.rb:27:in `walk'
	from lib/natalie/compiler/backends/cpp_backend/transform.rb:29:in `transform'
	from lib/natalie/compiler/backends/cpp_backend.rb:33:in `transform_instructions'
	from lib/natalie/compiler/backends/cpp_backend.rb:18:in `generate'
	from lib/natalie/compiler.rb:224:in `transform'
	from lib/natalie/compiler.rb:143:in `instructions'
	from lib/natalie/compiler.rb:102:in `write_file'
	from lib/natalie/compiler.rb:81:in `compile'
	from bin/natalie:139:in `run'
	from bin/natalie:305:in `<main>'
```
A few more ways to trigger this error (which all work in MRI)
```ruby
(a = 1) + a
(a = "") +  a
```
The following comparable statements have the same behaviour in MRI and Natalie:
```ruby
a = a # a => nil
a = "" + a # raises TypeError with message "no implicit conversion from nil to string"
a = "foo" + a.to_s # a => "foo", because a is nil before the assignment
```
I think the last one is the most interesting of the bunch, since adding parentheses causes Natalie to break again, which probably is the minimal change to trigger this error
```ruby
(a = "foo") + a.to_s
```
If the variable exists, the statement works, and the operations are done in correct order
```ruby
a = nil
(a = 1) + a # a => 1, return value => 2
```

**Comment by herwinw** [comment]
Once this is fixed, the change in `spec/library/set/shared/inspect.rb` can be reverted.

**Comment by seven1m** [comment]
The issue here is actually that the "receiver" of a call/message and the arguments are not evaluated in the expected order. It's surprising to me that we haven't noticed this before!

Here is a failing test for that:

```ruby
describe 'call order' do
  @order = []

  def first
    @order << 1
    1
  end

  def second
    @order << 2
    2
  end

  it 'evaluates the receiver before the arguments' do
    (first + second).should == 3
    @order.should == [1, 2]
  end
end
```
