### ISSUE TITLE
Random does not behave like the specs

### ISSUE THREAD

**Issue by herwinw** [natalie-lang/natalie#919]
An observation from #918

MRI's `Random` has a reproducible output based on the seed. The docs show a few examples, like:
```ruby
prng1 = Random.new(1234)
prng1.seed       #=> 1234
prng1.rand(100)  #=> 47
```
I can reproduce this to return 47 on my local machine's MRI. On Natalie, it return 19 for me.

The [documentation](https://ruby-doc.org/core-3.0.0/Random.html) (emphasis mine)
> PRNGs are currently implemented as a **modified** Mersenne Twister with a period of 2**19937-1.

It does not disclose how it has been altered, so I guess we'll need to distill that from the MRI source. I'm not sure what kind of legal (Copyright etc) implications that may have.

**Comment by seven1m** [comment]
This seems like an implementation detail. I'm surprised that specs are coded to expect certain random output.

I don't currently consider this a bug, but maybe there's some useful "feature" here I'm missing.

**Comment by herwinw** [comment]
I think that's more of a discussion for the ruby-spec list. As far as I could find, the `Random#bytes` spec was the only one that tested specific output, the other specs were all tests to see if the same seed yields the same output.

But given that it's in the spec so all other major implementations have the same output, there are probably people who depend on it. https://xkcd.com/1172/

**Comment by seven1m** [comment]
Fair point, but I'm also OK with being a little bit different here. Natalie can never be a 100% fully compatible Ruby. At the very least, I think we could shelve this until down the road when it is actually a problem for someone.

**Comment by herwinw** [comment]
I've finally added an issue in the ruby/spec repository about this issue (https://github.com/ruby/spec/issues/1051). I think we can close this issue for now, and create a new issue if we decide to handle this.

**Comment by eregon** [comment]
FYI: https://github.com/ruby/spec/issues/1051#issuecomment-1672902220
