### ISSUE TITLE
Convert NATFIXME comments in the specs into blocks

### ISSUE THREAD

**Issue by herwinw** [natalie-lang/natalie#963]
A lot of spec files in Natalie have `NATFIXME` comments to indicate something is not yet working. [An example](https://github.com/natalie-lang/natalie/blob/37b97c6675cfeddfa5f44f9f0b5b8a03c077b2b0/spec/core/rational/to_r_spec.rb):
```ruby
obj = BasicObject.new; def obj.to_r; 1 / 2.to_r end
# NATFIXME: Implement Rational(String)
# Rational(obj).should == Rational('1/2')
Rational(obj).should == Rational(1, 2)
```

These kind of comments can be replaced by [NATFIXME blocks](https://github.com/natalie-lang/natalie/blob/37b97c6675cfeddfa5f44f9f0b5b8a03c077b2b0/test/support/spec.rb), so it should read something like this
```ruby
obj = BasicObject.new; def obj.to_r; 1 / 2.to_r end
NATFIXME 'Implement Rational(String)', exception: ArgumentError do
  Rational(obj).should == Rational('1/2')
end
Rational(obj).should == Rational(1, 2)
```
This has the benefit of actually running the block and generating an error once the issue has been resolved, so we can update the spec to make it behave like the upstream specs again.

Not every block of disabled code can be converted, some code aborts the program, some code takes too long, that code should remain disabled.

You might find disabled tests that actually pass, or disabled tests with outdated comments. These can all be fixed.

# Directories with NATFIXME comments:

- [x] spec/command_line
- [x] spec/core/array
- [x] spec/core/basicobject
- [x] spec/core/class
- [x] spec/core/dir
- [x] spec/core/encoding
- [x] spec/core/enumerable
- [x] spec/core/enumerator
- [x] spec/core/enumerator/lazy
- [x] spec/core/file
- [x] spec/core/float
- [x] spec/core/hash
- [x] spec/core/integer
- [x] spec/core/kernel
- [x] spec/core/matchdata
- [x] spec/core/math
- [x] spec/core/method
- [x] spec/core/module
- [x] spec/core/process
- [x] spec/core/random
- [x] spec/core/range
- [x] spec/core/rational
- [x] spec/core/regexp
- [x] spec/core/string
- [x] spec/core/string/unpack
- [x] spec/core/struct
- [x] spec/core/symbol
- [x] spec/core/time
- [x] spec/language
- [x] spec/library/rbconfig
- [x] spec/library/set
- [x] spec/library/socket
- [x] spec/library/stringio
- [x] spec/library/zlib
- [x] spec/shared/rational
- [x] spec/shared/string

**Comment by nanobowers** [comment]
@herwinw  One of the unfortunate side effects of this NATFIXME implementation is that it hides the issues from view, whereas with the `xit` approach, you would see something like `......*.....*....` and `3 tests skipped`

Perhaps there is a way to have our mini-mspec mark the `it` blocks if there is a `NATFIXME` in them, so that the reporting is more obvious for passing cases where NATFIXME has hidden the issue, e.g. `......N.....N....` and `3 tests with NATFIXME` instead of marking all as `.` (pass).

**Comment by seven1m** [comment]
Yeah I was just noticing this too. I think NATFIXMEs could at least increment the skip count.

**Comment by nanobowers** [comment]
@seven1m  That should be easier than inventing a new type of test status (tentatively marked with `N` as noted above).  It could be useful to mark them differently in case someone cares about the difference between the NATFIXME's and `xit` specs that natively existed in ruby/spec.  OTOH, the output would diverge a bit more from what one might get with mspec/rspec.

**Comment by herwinw** [comment]
> Yeah I was just noticing this too. I think NATFIXMEs could at least increment the skip count.

I think it depends on the context to whether or not a NATFIXME should be counted as a skip or not. Take the example of `Rational('1/2')` in the example code in this issue: The code passes, it's just that the RHS of the test in the spec is not yet supported, so we replaced it with another way of getting a rational of `1/2` and we test everything the spec is supposed to test.
I think using a different output, like the suggested `N`, would be a less ambiguous output.

Also: I don't think the way the test output is shown should be blocking for rewriting the comments into blocks, so I think this should be in its own issue.

**Comment by herwinw** [comment]
And that was all. We still have a number of specs disabled or commented, but those result in panics or infinite loops.
