### ISSUE TITLE
Document best practices regarding code and specs

### ISSUE THREAD

**Issue by herwinw** [natalie-lang/natalie#972]
(Split from a discussion in #964)

The current [CONTRIBUTING](https://github.com/natalie-lang/natalie/blob/master/CONTRIBUTING.md) document is very short and generic. There are a  lot of best practices we're using in the project that are not mentioned anywhere. A non exhaustive list:
* Disabling failing specs with `NATFIXME`, `xit`, `xdescribe` etc.
* Coding styles, both C++ and Ruby

**Comment by nanobowers** [comment]
Also would be nice to document #874

There are probably other best practices that people are using that are not currently part of the project that might make it more convenient for testing and development, unsure what the best way to discuss that is besides submitting PRs.

**Comment by seven1m** [comment]
I opened #1061 to improve our doc. Please let me know if you think I missed anything!

**Comment by nanobowers** [comment]
I didn't realize there was a rubocop config for the project until I read the changes in #1061 
Would it be appropriate to add `rubocop --auto-correct` to the `rake format` task or is that too heavy handed?

**Comment by seven1m** [comment]
Unfortunately, Rubocop breaks some stuff when it auto-corrects. I just now ran it on the whole project, and after the "corrections" I started seeing this error:

```sh
→ bin/natalie examples/hello.rb
/home/tim/pp/natalie/lib/natalie/compiler.rb:9:in `require_relative': /home/tim/pp/natalie/lib/natalie/compiler/macro_expander.rb:230: syntax error, unexpected string literal, expecting `end' (SyntaxError)
...init_function) : $stderr.puts "Expected #{path} to contain f...
...                              ^
        from /home/tim/pp/natalie/lib/natalie/compiler.rb:9:in `<top (required)>'
        from /home/tim/pp/natalie/lib/natalie.rb:1:in `require_relative'
        from /home/tim/pp/natalie/lib/natalie.rb:1:in `<top (required)>'
        from bin/natalie:15:in `require_relative'
        from bin/natalie:15:in `<main>'
```

In the past I had tried to use [prettier](https://github.com/prettier/plugin-ruby) to autoformat Ruby code, but I strongly disagree with many of its decisions and feel like it makes the code _harder_ to read in many places.

I think for now, I'd prefer to have slightly-less consistent Ruby (even if that means people forget to run `rubocop`) than to have code auto-formatted that's hard to read or perhaps broken. 😄
