### ISSUE TITLE
Natalie does not preserve method access modifiers in inheritance

### ISSUE THREAD

**Issue by herwinw** [natalie-lang/natalie#998]
Take the following script:
```ruby
class Foo
end
p Foo.private_instance_methods.include?(:initialize)

class Bar
  def initialize
  end
end
p Bar.private_instance_methods.include?(:initialize)
```
Because `BasicObject#initialize` is private, `Object#initialize` and `Foo#initialize` are private too. `Bar` overrides the `initialize` method, MRI keeps the method private, but Natalie makes it public. In other words: This script prints "true, true" in MRI and "true, false" in Natalie.

There are a lot of specs trying to see if `initialize` is private, we should probably make a generic fix for this.

**Comment by seven1m** [comment]
This appears to only affect the `initialize` method, yes? If I make a `foo` method on a parent class and mark it private, defining a `foo` method on a subclass without marking it private causes it to be public again.

```
class Foo
  private
  def foo
    'foo'
  end
end
p Foo.private_instance_methods.include?(:foo)        # => true (both Natalie and MRI)
p Foo.private_instance_methods.include?(:initialize) # => true (both Natalie and MRI)

class Bar
  def initialize
  end

  def foo
    'foo'
  end
end
p Bar.private_instance_methods.include?(:foo)        # => false (both Natalie and MRI)
p Bar.private_instance_methods.include?(:initialize) # => true in MRI, false in Natalie
```

In fact, it seems that `initialize` is always private, no matter what I tell Ruby:

```
class Baz
  public
  def initialize
  end
end

p Baz.private_instance_methods.include?(:initialize) # => true in MRI
```

So this might not be an inheritance thing.

**Comment by seven1m** [comment]
Clarification, you can make the `initialize` method public by using the `Module#public` method, passing in the name :initialize.

```ruby
class Baz
  def initialize
  end
  public :initialize
end

p Baz.private_instance_methods.include?(:initialize) # => false
p Baz.public_instance_methods.include?(:initialize)  # => true
```
